apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}
spec:
  commonName: {{ .Values.virtualhost.fqdn }}
  dnsNames:
    -  {{ .Values.virtualhost.fqdn }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: {{ .Values.name }}