kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
spec:
  ports:
    - name: http1
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type}}
status:
  loadBalancer: {}